### ISSUE TITLE
Disable StatusPage status change on errors

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/browbeat#95]
Changing status (i.e. major outage, partial, etc.) in StatusPage is part of the "report incident" functionality in StatusPage and has enough nuance that it should be managed by an individual instead of Browbeat. The automation in Browbeat can also cause conflicts between what is marked down by a person and what is marked up by Browbeat, for example.

## Acceptance Criteria

- Disable statuspage API posts from Browbeat
- Use cucumber's [rerun formatter](https://relishapp.com/cucumber/cucumber/docs/formatters/rerun-formatter) to keep track of failed tests
  - Failed tests write to rerun file on persistent storage
  - Next "failed jobs" cron uses the rerun file to only rerun those tests
  - **Note:** This will require some persistent storage in Browbeat container crons (EBS?)

**Comment by ericgriffis** [comment]
Closing this as we've disable status page change on errors; moving ideas for new persistence layer to another issue
